# Generated by Django 5.0.4 on 2024-04-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referal_points',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
