# Generated by Django 5.0.4 on 2024-04-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_referal_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referal_code',
            new_name='my_referal_code',
        ),
    ]
