# Generated by Django 5.0.4 on 2024-04-07 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referals',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
