# Generated by Django 5.0.4 on 2024-04-07 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_referals_user_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referals', to=settings.AUTH_USER_MODEL),
        ),
    ]
